<?php

/**
 * BasePlace
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $place_name
 * @property integer $maximum_capacity
 * @property Doctrine_Collection $ClassesForPlace
 * 
 * @method string              getPlaceName()        Returns the current record's "place_name" value
 * @method integer             getMaximumCapacity()  Returns the current record's "maximum_capacity" value
 * @method Doctrine_Collection getClassesForPlace()  Returns the current record's "ClassesForPlace" collection
 * @method Place               setPlaceName()        Sets the current record's "place_name" value
 * @method Place               setMaximumCapacity()  Sets the current record's "maximum_capacity" value
 * @method Place               setClassesForPlace()  Sets the current record's "ClassesForPlace" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlace extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('place');
        $this->hasColumn('place_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('maximum_capacity', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AbstractClass as ClassesForPlace', array(
             'local' => 'id',
             'foreign' => 'place_id'));
    }
}