<?php

/**
 * BaseClassPerCoach
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $coach_id
 * @property integer $abstract_class_id
 * @property Coach $Coach
 * @property AbstractClass $AbstractClass
 * 
 * @method integer       getCoachId()           Returns the current record's "coach_id" value
 * @method integer       getAbstractClassId()   Returns the current record's "abstract_class_id" value
 * @method Coach         getCoach()             Returns the current record's "Coach" value
 * @method AbstractClass getAbstractClass()     Returns the current record's "AbstractClass" value
 * @method ClassPerCoach setCoachId()           Sets the current record's "coach_id" value
 * @method ClassPerCoach setAbstractClassId()   Sets the current record's "abstract_class_id" value
 * @method ClassPerCoach setCoach()             Sets the current record's "Coach" value
 * @method ClassPerCoach setAbstractClass()     Sets the current record's "AbstractClass" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClassPerCoach extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('class_per_coach');
        $this->hasColumn('coach_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('abstract_class_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Coach', array(
             'local' => 'coach_id',
             'foreign' => 'id'));

        $this->hasOne('AbstractClass', array(
             'local' => 'abstract_class_id',
             'foreign' => 'id'));
    }
}