<?php

/**
 * BaseClassPerClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property integer $abstract_class_id
 * @property Client $Client
 * @property AbstractClass $AbstractClass
 * 
 * @method integer        getClientId()          Returns the current record's "client_id" value
 * @method integer        getAbstractClassId()   Returns the current record's "abstract_class_id" value
 * @method Client         getClient()            Returns the current record's "Client" value
 * @method AbstractClass  getAbstractClass()     Returns the current record's "AbstractClass" value
 * @method ClassPerClient setClientId()          Sets the current record's "client_id" value
 * @method ClassPerClient setAbstractClassId()   Sets the current record's "abstract_class_id" value
 * @method ClassPerClient setClient()            Sets the current record's "Client" value
 * @method ClassPerClient setAbstractClass()     Sets the current record's "AbstractClass" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClassPerClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('class_per_client');
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('abstract_class_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('AbstractClass', array(
             'local' => 'abstract_class_id',
             'foreign' => 'id'));
    }
}