<?php

/**
 * BaseAbstractPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property date $birthday
 * @property string $email
 * @property string $address
 * @property string $phones
 * 
 * @method string         getFirstName()  Returns the current record's "first_name" value
 * @method string         getLastName()   Returns the current record's "last_name" value
 * @method date           getBirthday()   Returns the current record's "birthday" value
 * @method string         getEmail()      Returns the current record's "email" value
 * @method string         getAddress()    Returns the current record's "address" value
 * @method string         getPhones()     Returns the current record's "phones" value
 * @method AbstractPerson setFirstName()  Sets the current record's "first_name" value
 * @method AbstractPerson setLastName()   Sets the current record's "last_name" value
 * @method AbstractPerson setBirthday()   Sets the current record's "birthday" value
 * @method AbstractPerson setEmail()      Sets the current record's "email" value
 * @method AbstractPerson setAddress()    Sets the current record's "address" value
 * @method AbstractPerson setPhones()     Sets the current record's "phones" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAbstractPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('abstract_person');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phones', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}