<?php

/**
 * BaseClassType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type_name
 * @property Doctrine_Collection $ClassesofType
 * 
 * @method string              getTypeName()      Returns the current record's "type_name" value
 * @method Doctrine_Collection getClassesofType() Returns the current record's "ClassesofType" collection
 * @method ClassType           setTypeName()      Sets the current record's "type_name" value
 * @method ClassType           setClassesofType() Sets the current record's "ClassesofType" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClassType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('class_type');
        $this->hasColumn('type_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AbstractClass as ClassesofType', array(
             'local' => 'id',
             'foreign' => 'class_type_id'));
    }
}