<?php

/**
 * BaseMembershipFee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property date $date
 * @property float $amount
 * @property Client $Client
 * 
 * @method integer       getClientId()  Returns the current record's "client_id" value
 * @method date          getDate()      Returns the current record's "date" value
 * @method float         getAmount()    Returns the current record's "amount" value
 * @method Client        getClient()    Returns the current record's "Client" value
 * @method MembershipFee setClientId()  Sets the current record's "client_id" value
 * @method MembershipFee setDate()      Sets the current record's "date" value
 * @method MembershipFee setAmount()    Sets the current record's "amount" value
 * @method MembershipFee setClient()    Sets the current record's "Client" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMembershipFee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('membership_fee');
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('amount', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));
    }
}