<?php

/**
 * BaseClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Classes
 * @property Doctrine_Collection $ClassesPerClient
 * @property Doctrine_Collection $MedicalRevisions
 * @property Doctrine_Collection $MembershipFees
 * 
 * @method Doctrine_Collection getClasses()          Returns the current record's "Classes" collection
 * @method Doctrine_Collection getClassesPerClient() Returns the current record's "ClassesPerClient" collection
 * @method Doctrine_Collection getMedicalRevisions() Returns the current record's "MedicalRevisions" collection
 * @method Doctrine_Collection getMembershipFees()   Returns the current record's "MembershipFees" collection
 * @method Client              setClasses()          Sets the current record's "Classes" collection
 * @method Client              setClassesPerClient() Sets the current record's "ClassesPerClient" collection
 * @method Client              setMedicalRevisions() Sets the current record's "MedicalRevisions" collection
 * @method Client              setMembershipFees()   Sets the current record's "MembershipFees" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClient extends AbstractPerson
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('client');

        $this->setAttribute(Doctrine_Core::ATTR_EXPORT, Doctrine_Core::EXPORT_ALL);
        $this->setAttribute(Doctrine_Core::ATTR_VALIDATE, true);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AbstractClass as Classes', array(
             'refClass' => 'ClassPerClient',
             'local' => 'client_id',
             'foreign' => 'abstract_class_id'));

        $this->hasMany('ClassPerClient as ClassesPerClient', array(
             'local' => 'id',
             'foreign' => 'client_id'));

        $this->hasMany('MedicalRevision as MedicalRevisions', array(
             'local' => 'id',
             'foreign' => 'client_id'));

        $this->hasMany('MembershipFee as MembershipFees', array(
             'local' => 'id',
             'foreign' => 'client_id'));
    }
}