<?php

/**
 * AbstractClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AbstractClassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AbstractClassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AbstractClass');
    }
    
    public function getClassesForPlace(Place $place) {
    	  $q = Doctrine_Query::create()
    		->from('AbstractClass class')
    		->where('class.place_id = ?', $place->getId());
    	return $q->execute();
    }
    
    
}