<?php

/**
 * AbstractPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AbstractPersonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AbstractPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AbstractPerson');
    }
}