<?php

/**
 * ClassPerClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClassPerClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClassPerClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClassPerClient');
    }
}