<?php

/**
 * MembershipFeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MembershipFeeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MembershipFeeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MembershipFee');
    }
}