<?php

/**
 * AbstractClass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AbstractClass extends BaseAbstractClass
{
	function getPlaceName() {
		return $this->getPlace()->getPlaceName();
	}
	function getClassTypeName() {
		return $this->getClassType()->getTypeName();
	}
	function getStartTime() {
		return $this->getStartHour().":".(($this->getStartMin() == 0)?"00":$this->getStartMin());
	}
	function getEndTime() {
		return $this->getEndHour().":".(($this->getEndMin() == 0)?"00":$this->getEndMin());
	}
	function getCountClients() {
		return count($this->getClients());		
	}
	
	function __toString() {
		return $this->getDayOfTheWeek()." ".$this->getStartTime()."-".$this->getEndTime();	
	}
}
