<?php

/**
 * ClassPerCoachTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClassPerCoachTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClassPerCoachTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClassPerCoach');
    }
}