<?php

/**
 * MedicalRevisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicalRevisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicalRevisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedicalRevision');
    }
}